### ISSUE TITLE
Silently swallows %=

### ISSUE THREAD

**Issue by gustaphe** [scr1pt0r/crease.vim#1]
I can't get the alignment characters to work. This code

```
set fillchars=fold:─
let g:crease_foldtext = { 'default': '%f%f%f┤ %t ├%=┤ %%= %%%= ├%=┤ %l lines ├' }
```

results in
```
───┤ text ├┤ % % ├┤ 5 lines ├───────<fill to end>
```

I can see why the `split` method removes escaped `%%=`, and I don't think that's a terrible loss, but it's a shame to miss out on alignment.

I'm on Arch Linux, using Vim in the Terminator terminal.

**Comment by scr1pt0r** [comment]
For me this code results in:
```
───┤ text ├─<fill>─┤ %─<fill>─ %─<fill>─ ├─<fill>─┤ 5 line ├
```
Which is what should be doing write now, since my code doesn't escape "%%=" correctly. I'm working on a fix to escape "%%=" correctly into '%=".

What is the version of your vim?

**Comment by gustaphe** [comment]
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23)
Included patches: 1-814
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
[...]
```

(I included the `%%=` stuff because that's what I was testing with, I didn't realize they didn't matter until I was about to hit send on the issue. I don't think that's important)

**Comment by gustaphe** [comment]
I wrote a more global version of your script, and it seems like what happens is it fails at GitGutterGetHunks. Installing https://github.com/airblade/vim-gitgutter did the trick.

**Comment by scr1pt0r** [comment]
Yes, I just realized that this is the problem. The plugin checks if `g:loaded_gitgutter` is `1`, to check if this plugin is loaded, but the problem is that if this plugin isn't installed, this variable isn't defined. Pushing a fix (for both issues you've mentioned).

**Comment by gustaphe** [comment]
It's a neat plugin, I don't mind having installed it at all :)
