### ISSUE TITLE
Syntax highlighting bug after :set spell

### ISSUE THREAD

**Issue by danielfalbo** [scr1pt0r/crease.vim#3]
Is this an issue on your machines too or have I screwed something up?

![Screen-Recording-2020-11-16-at-1](https://user-images.githubusercontent.com/39460524/99287315-61441c80-283a-11eb-9dcd-33bd8fe15265.gif)

**Comment by scr1pt0r** [comment]
This is not an issue on my machine. I think you must have screwed something up in your own configuration. Please uninstall this plugin and check if the issue persists.

Do you manually set the `Folded` highlight group? My guess is that `:set spell` somehow refreshes or updates your highlights which you set incorrectly, so `Folded` is reset to `Normal`.

**Comment by danielfalbo** [comment]
The issue is not present anymore on my machine with the latest nightly neovim update 🚀👍
