### ISSUE TITLE
How to customise the fold text color.

### ISSUE THREAD

**Issue by goncalves-diogo** [scr1pt0r/crease.vim#4]
Hi, Can you please share how to change the default white text from the fold?

<img width="832" alt="Screenshot 2021-08-16 at 20 50 54" src="https://user-images.githubusercontent.com/33640150/129621520-6b044da5-1dc7-496f-9f7a-53d5f51b5bcd.png">

In the previous image you can see the text is just regular white, Can it be for the outside to match changed to match the comment.

<img width="665" alt="Screenshot 2021-08-16 at 20 55 04" src="https://user-images.githubusercontent.com/33640150/129621953-f0ab51fb-1cf0-4ac5-80ad-5aec1e40d19b.png">

I want something that will the colours of the previous image. Do you know how to do it, or can you guide me in any direction?

Thank you in advance for your time, and thank you for the plugin

**Comment by scr1pt0r** [comment]
If I understand correctly, you would like to customize the foldtext highlighting to match the colors of the second image? Unfortunately, vim does not allow highlighting different parts of the foldtext. You can highlight the whole foldtext with the `Folded` highlight group.

**Comment by goncalves-diogo** [comment]
I've looked deeper into it and I believe you are correct, thanks for the response.
